name: Node SDK - Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Test, build and deploy to npm
    if: ${{ !contains(github.event.head_commit.message, 'norelease') }}
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@main

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      - name: Generate new tag (dry run)
        uses: mathieudutour/github-tag-action@v6.1
        id: get_new_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Update npm package version
        run: |
          npm version ${{ steps.get_new_version.outputs.new_version }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bumped npm package version to ${{ steps.get_new_version.outputs.new_version }}

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        id: create_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release to npm
        working-directory: ./build
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
